# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install cookiecutter
      run: |
        python -m pip install --upgrade pip
        python -m pip install cookiecutter
    - name: Try to install the template
      run: |
        printf "\n\n\n\n\n" | cookiecutter https://github.com/sodascience/metasyn-plugin-template
    - name: Check installation
      run: |
        test -d metasyn-differential-privacy
        cd metasyn-differential-privacy
        pip install .
